spring:
  datasource:
    url: jdbc:mysql://183.237.21.252:13306/mysqltest
    username: mysqltest
    password: mysqltest
    
    hikari:
      validation-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
      max-lifetime: 30000
#    fro   
#    druid:
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      min-evictable-idle-time-millis: 30000
#      time-between-connect-error-millis: 60000
#    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:  
#    hibernate:
#      ddl-auto: update


  data:
    mongodb:
      host: 183.237.21.252
      port: 27017
      database: admin
#      authentication-database: Test_Mongodb
      username: mongo-admin
      password: mongo-password
#      username: test
#      password: 123456
      
      
  redis:
    host: 183.237.21.252
    port: 6379
    database: 2
    
    lettuce:
      pool:
        max-total: 5
        max-active: 5
        max-idle: 5
        min-idle: 1
        max-wait: 5000        
        
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
       
   
logging:
  level:
#    root: debug
    org.hibernate.SQL: debug
server:
  port: 443
  ssl:
    key-store: D:/代码\充电管理平台/ScanWebApp2/scanWebApp/src/main/resources/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat

emqtt:
  server: 39.108.7.234
  port: 61613 

wxconfig:
  appid: wx9de5e895e731c84c
  secret: 77681fcc30d6516585b937402391fe39
  token: 111
  aesKey: 111
  msgDataFormat: JSON

  mchId:
  mchKey:
  subAppId:
  subMchId:
  keyPath:    